# Generated by Django 3.2.18 on 2023-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='user_email',
        ),
    ]
