# Generated by Django 3.2.18 on 2023-05-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.table'),
        ),
    ]
