# Generated by Django 3.2.18 on 2023-05-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_tableavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
    ]
