# Generated by Django 3.2.18 on 2023-05-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_email',
            new_name='user_id',
        ),
    ]
