# Generated by Django 3.2.18 on 2023-05-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_rename_user_email_booking_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
