# Generated by Django 3.2.18 on 2023-05-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
    ]
