# Generated by Django 3.2.18 on 2023-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
