# Generated by Django 3.2.18 on 2023-05-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableavailability',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
