# Generated by Django 3.2.18 on 2023-05-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_tableavailability_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableavailability',
            name='booking',
        ),
    ]
