# Generated by Django 3.2.18 on 2023-05-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_tableavailability_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableavailability',
            options={'verbose_name_plural': 'Table Availabilities'},
        ),
    ]
