# Generated by Django 3.2.18 on 2023-05-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_tableavailability_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableavailability',
            old_name='booking',
            new_name='booking_id',
        ),
    ]
