# Generated by Django 3.2.18 on 2023-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_rename_booking_tableavailability_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
