# Generated by Django 3.2.18 on 2023-05-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_tableavailability_id_of_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableavailability',
            name='is_available',
        ),
    ]
