# Generated by Django 3.2 on 2023-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_auto_20230624_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='location_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='location_y',
            field=models.IntegerField(default=0),
        ),
    ]
