# Generated by Django 3.2 on 2023-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_auto_20230625_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='table',
            name='location_y',
        ),
        migrations.AddField(
            model_name='table',
            name='left',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='top',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
