# Generated by Django 3.2 on 2023-06-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_auto_20230625_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='left',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='top',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
