# Generated by Django 3.2 on 2023-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_auto_20230625_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='left',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='top',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
